### ISSUE TITLE
custom-elements-manifest.config.js

### ISSUE THREAD

**Issue by husayt** [Kamiapp-fr/vite-plugin-cem#10]
Is this plugin able to use config from "custom-elements-manifest.config.js"  same way as command line alternative would?

Thanks

**Comment by EmilienLeroy** [comment]
Hi @husayt 

Currently, this feature is not supported. If you wish, you can open a pull request to add support for a configuration file. Otherwise, I will attempt to work on this in the next few weeks.

**Comment by husayt** [comment]
excellent will be looking forward. For now this did the job for me::

```js
import cemConfig from './custom-elements-manifest.config.js';

export default defineConfig(({ mode }) => ({
...
  plugins: [
    VitePluginCustomElementsManifest({
      files: cemConfig.globs,
      // files: ['./src/sx.ts'],
      lit: true,
      packageJson: true,
      plugins: cemConfig.plugins
    })
    ]
    }
```

**Comment by EmilienLeroy** [comment]
Hi @husayt 
I have just released a [new version](https://github.com/Kamiapp-fr/vite-plugin-cem/releases/tag/v0.8.0) that includes support for the `custom-elements-manifest.config.js` file.  
Could you test this version to confirm if it meets your requirements?
