### ISSUE TITLE
Find files by pattern match instead of concrete entries

### ISSUE THREAD

**Issue by adaliszk** [Kamiapp-fr/vite-plugin-cem#5]
When developing packages with multiple elements, it would be beneficial if the plugin would pick up the custom element files automatically by providing a pattern list so that there would be no need to modify the Vite configuration whenever a new element is added or the existing ones get refactored into different locations.

I see this achieved easily by adding a dependency to `glob` and using it to provide a file list.
Alternatively, `fs` could list the files and match them with regexp patterns. Optimally by using the basepath within the patterns.

**Comment by EmilienLeroy** [comment]
Hello @adaliszk 
I appreciate your interest in this plugin. I'm agree that incorporating this feature would be a valuable addition. I plan to implement it when I have an opportunity.

**Comment by EmilienLeroy** [comment]
Hello @adaliszk 
I just release the [v0.5.0](https://github.com/Kamiapp-fr/vite-plugin-cem/releases/tag/v0.5.0) of the plugin, which allow you to use pattern !

**Comment by adaliszk** [comment]
Thank you @EmilienLeroy!
