### ISSUE TITLE
Generate custom-elements.json on the filesystem for development

### ISSUE THREAD

**Issue by adaliszk** [Kamiapp-fr/vite-plugin-cem#6]
While the plugin does provide a `/custom-elements.json` for development, documentation tools like Storybooks would benefit from a local path import to initialize its automatic generator.

### Current solution:

```typescript
// .storybook/preview.ts

import { setCustomElementsManifest } from '@storybook/web-components'

fetch('/custom-elements.json')
    .then(res => res.json())
    .then(customElements => setCustomElementsManifest(customElements))
```

### Desired solution:

```typescript
// .storybook/preview.ts

import { setCustomElementsManifest } from '@storybook/web-components'
import customElements from '../dist/custom-elements.json'

setCustomElementsManifest(customElements)
```

Alternatively, a custom resolver could be used to achieve:

```typescript
// .storybook/preview.ts

import { setCustomElementsManifest } from '@storybook/web-components'
import customElements from '@custom-elements.json'

setCustomElementsManifest(customElements)
```

### Use-case

As a Component Developer, I use storybooks with lit custom elements, and I wish to generate the documentation to decrease the authoring burden automatically. This can be more-less done by using storybooks automatic documentation generator when the custom elements manifest is provided. However, additional integrations require a non-promise flow or top-level await.

For example, to use [`cem-plugin-better-lit-types`](https://www.npmjs.com/package/cem-plugin-better-lit-types) one needs to resolve the manifest and then pass it to the top-level parameters export in storybooks:
```typescript
// .storybook/preview.ts
import { setCustomElementsManifest } from '@storybook/web-components'
import { createArgsExtractor, createLitRenderer } from 'cem-plugin-better-lit-types/storybook'
import customElements from '../custom-elements.json'

export const parameters = {
  docs: {
    extractArgTypes: createArgsExtractor(customElements),
  }
}

/**
 * Custom renderer made specially for LitComponents  
 */
export const render = createLitRenderer({
  wrapSlots: true, // Wraps a non-default slot in `<span slot="name">`
  joinArray: true,  // Converts array to a comma-separated string
})
```

**Comment by EmilienLeroy** [comment]
@adaliszk 
I understand the benefits of this feature, but I personally don't utilize tools such as Storybook. However, pull requests are welcome if you would like to add it. Perhaps it could be an option like `buildOnDev` or similar.

**Comment by adaliszk** [comment]
Looks like a perfect solution, sorry that I didn't follow up earlier!
